from __future__ import annotations

from pathlib import Path

import streamlit as st

from components.cards import render_section_header
from components.sidebar import render_sidebar
from components.tables import render_artifact_card, render_artifact_grid, render_markdown_preview
from components.utils import (
    APP_ROOT,
    DATA_DIR,
    FIGURES_DIR,
    MODELS_DIR,
    PROCESSED_DATA_DIR,
    PROCESSED_DIR,
    REPORTS_DIR,
    bootstrap_page,
    file_bytes,
    list_artifacts,
    list_figures,
    list_models,
    list_reports,
    read_text,
)


def _combine_csv_artifacts() -> list:
    exclude_names = {
        "retailpulse_processed.csv",
        "recommendation_scores.csv",
        "scenario_analysis.csv",
        "risk_summary.csv",
        "priority_actions.csv",
        "business_alerts.csv",
        "business_decisions.csv",
        "executive_summary.csv"
    }
    csv_artifacts = list_artifacts(PROCESSED_DIR, (".csv",), exclude_backup=True)
    csv_artifacts.extend(list_artifacts(PROCESSED_DATA_DIR, (".csv",), exclude_backup=True))
    unique: dict[str, object] = {}
    for entry in csv_artifacts:
        if entry.name in exclude_names:
            continue
        unique.setdefault(entry.name, entry)
    return sorted(unique.values(), key=lambda item: item.modified, reverse=True)



theme_mode = bootstrap_page("Report Center", "📚")
reports = list_reports()
figures = list_figures()
models = list_models()
csvs = _combine_csv_artifacts()

render_sidebar(
    theme_mode=theme_mode,
    page_label="Report Center",
    summary={
        "CSV": str(len(csvs)),
        "Reports": str(len(reports)),
        "Figures": str(len(figures)),
    },
)

st.markdown(
    """
<div class="rp-hero">
  <div class="rp-hero-title">Report Center</div>
  <div class="rp-hero-subtitle">Download the processed CSVs, markdown reports, and generated figures that power the platform.</div>
</div>
""",
    unsafe_allow_html=True,
)

query = st.text_input("Search artifacts", placeholder="Filter by file name")
normalized = query.lower().strip()

def _filter_entries(entries):
    if not normalized:
        return entries
    return [entry for entry in entries if normalized in entry.name.lower()]


csvs = _filter_entries(csvs)
reports = _filter_entries(reports)
figures = _filter_entries(figures)
models = _filter_entries(models)

tabs = st.tabs(["CSV", "Markdown", "Figures", "Models"])
with tabs[0]:
    render_section_header("CSV Downloads", "Processed dataset outputs from the completed phases.")
    render_artifact_grid(csvs, columns=3, download_label="Download CSV")
with tabs[1]:
    render_section_header("Markdown Reports", "Business and technical reports generated by the pipeline.")
    render_artifact_grid(reports, columns=3, download_label="Download report")
    if reports:
        chosen = st.selectbox("Preview report", [entry.name for entry in reports], index=0)
        selected = next(entry for entry in reports if entry.name == chosen)
        if selected.name.endswith(".html"):
            html_content = read_text(selected.path)
            st.components.v1.html(html_content, height=800, scrolling=True)
        else:
            render_markdown_preview(selected.path)
with tabs[2]:
    render_section_header("Generated Figures", "PNG and image assets ready for download.")
    render_artifact_grid(figures, columns=3, download_label="Download figure")
    if figures:
        chosen = st.selectbox("Preview figure", [entry.name for entry in figures], index=0)
        selected = next(entry for entry in figures if entry.name == chosen)
        st.image(file_bytes(selected.path))
with tabs[3]:
    render_section_header("Model Artifacts", "Saved model files and governance artifacts.")
    render_artifact_grid(models, columns=3, download_label="Download model")

